# -------------------------------------------------
# Tests with Makefile.var should run even on older GNU Make versions, e.g., version 3.81
# on macos. For this reason there I don't use the following operators:
# 1. ::= (introduced in GNU Make 4.0.0)
#    https://lists.gnu.org/archive/html/help-make/2013-10/msg00011.html
# 2. :::= (introduced in GNU Make 4.4.0)
#    https://lists.gnu.org/archive/html/help-make/2022-10/msg00020.html
# -------------------------------------------------

AWK := awk

.PHONY: help
help: ## show this help
	@bin/$(AWK) -f ../makefile-doc.awk $(MAKEFILE_LIST)

##@
##@ ----- recursive assignments
##@

## recursive assignment 1
a1 = 1

## recursive assignment 2
a2=1

   a3=1## recursive assignment inline

a4=1 ##another recursive assignment inline

  a4  = $(a3) ##%    recursive assignment -- a mess

##@
##@ ----- simply expanded variables with :=
##@

## simply expanded variable 1
b1 := 1

## simply expanded variable 1
b2:=1

   b3:=1## simply expanded variable inline

b4:=1 ##another simply expanded variable inline

  b4  := $(b3) ##%    simply expanded -- a mess

##@
##@ ----- simply expanded variables with ::=
##@

## simply expanded variable 1
c1 ::= 1

## simply expanded variable 1
c2::=1

   c3::=1## simply expanded variable inline

c4::=1 ##another simply expanded variable inline

  c4  ::= $(c3) ##%    simply expanded -- a mess

##@
##@ ----- immediately expanded variable
##@

## immediately expanded variable 1
d1 :::= 1

## immediately expanded variable 1
d2:::=1

   d3:::=1## immediately expanded variable inline

d4:::=1 ##another immediately expanded variable inline

  d4  :::= $(d3) ##%    immediately expanded -- a mess
