## 1234 5678\
1234 5678\
maybe we should allow this for form top docs in the future\
1234 5678
t-no-docs: # This will not have docs

## 1234 5678\
1234 5678\
1234 5678\
1234 5678
t-with-docs: ## Include in the docs because of the inline description

## 987
vvv0 := 1 ## 0
z0:
	@echo $(vvv1)

## 987\
vvv1 := 1 ## 1
z1:
	@echo $(vvv1)

## 987\\
vvv2 := 1 ## 2
z2:
	@echo $(vvv2)

## 987\\\
vvv3 := 1 ## 3
z3:
	@echo $(vvv3)

## 987\\\\
vvv4 := 1 ## 4
z4:
	@echo $(vvv4)

## 987\\\\\
vvv5 := 1 ## 5
z5:
	@echo $(vvv5)

## Spaces\ \
sss2 := 1 ## 2
s2:
	@echo $(sss2)

## Spaces\ \   \ \
sss3 := 1 ## 3
s3:
	@echo $(sss3)

## should ignore this comment and the variable
## which is a part of the above recipe
	BAD := 1

z6: X:=1
z6: Y:=2
z6: Z:=3
z6:
	@echo 1

# stuff \
more stuff

	@echo 1

#S:=1

## kkk
	@yes: ## BAD

## stuff \
more stuff\
## d|
BAD := 1
