# ======================================================================================
# Test grouped targets
# ======================================================================================

##@
##@ ----- Independent Targets -----
##@

first second: ## two targets

## other two targets
a b  :

##@
##@ ----- Grouped Targets -----
##@

## four grouped targets
me myself and I  &:

the show must go on&:    ## five grouped targets

## a bit pointless grouping one target
lonely &:## but it works (not displayed)

##@
##@ ----- Double-colon grouped Targets -----
##@

## two grouped targets with double-colon (version 1)
yes no&::

yes no  &:: ##! two grouped targets with double-colon (version 2)

yes no    &:: ##% two grouped targets with double-colon (version 3)
