# ======================================================================================
# Test double-colon targets
# ======================================================================================

##@
##@ ----- Single-colon targets -----
##@

##% some target
single-colon-A:

single-colon-B: ##% some other target

##@
##@ ----- Double-column targets -----
##@

## This is the first double-colon target from group A
## It has two lines of description
double-colon-A::

double-colon-B:: ##! group B first documented

double-colon-B:: # not documented

double-colon-B:: ## group B second documented

double-colon-A:: ## This is the second double-colon target from group A

double-colon-B:: ##% group B third documented (deprecated)

## This is a top doc for dc1~1
dc1:: ## this is inline (not shown) still dc1~1
dc1:: ## ...  still dc1~1
dc1:: ## ...  still dc1~1

dc1:: ## this is dc1~2
dc1:: ## ... dc1~2
dc1:: ## ... dc1~2
